# Generated by Django 3.2.5 on 2022-04-13 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myinspiration', '0010_auto_20220413_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='signup_confirmation',
        ),
    ]
