# Generated by Django 3.2.5 on 2022-05-02 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myinspiration', '0015_rename_profile_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Profile',
        ),
        migrations.RemoveField(
            model_name='inspirations',
            name='user',
        ),
        migrations.DeleteModel(
            name='Favoritos',
        ),
        migrations.DeleteModel(
            name='Inspirations',
        ),
    ]
