# Generated by Django 3.2.5 on 2022-05-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinspiration', '0017_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contrasena',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
