# Generated by Django 3.2.5 on 2022-05-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinspiration', '0027_alter_seguidos_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
