# Generated by Django 3.2.5 on 2022-04-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinspiration', '0012_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
