# Generated by Django 3.2.5 on 2022-05-16 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myinspiration', '0019_remove_profile_contrasena'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='last_name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='nombre_usuario',
        ),
    ]
