# Generated by Django 3.2.5 on 2022-05-19 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myinspiration', '0023_auto_20220516_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nombre_usuario',
        ),
    ]
