# Generated by Django 3.2.5 on 2022-05-22 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myinspiration', '0024_remove_profile_nombre_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='apellido',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='nombre',
            new_name='last_name',
        ),
    ]
